version: '3.7'

services:
  # Build the app services
  app:
    build: .
    volumes:
      - .:/usr/src/app/
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - ./.env
    entrypoint: sh entrypoint.sh
    network_mode: "host"
